spring:
  application:
    name: SampleDiDi

mvf4ms:
  version: 2.1.0
  dependencies:
    - name: dependency1
      dependence:
        - id: weather
          function: weather
          slas:
            - 3
        - id: pay
          function: pay
          slas:
            - 4

server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://{REGISTRY}/eureka
